# Generated by Django 5.1.2 on 2024-10-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description_generée',
            field=models.TextField(blank=True, null=True),
        ),
    ]
