# Generated by Django 5.1.2 on 2024-10-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorpic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='reclamation',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='Reclamation',
        ),
    ]
